using Workerd = import "/workerd/workerd.capnp";
const config :Workerd.Config = (
  services = [
    (name = "controller", worker = .controller),
    (name = "host", external = (address = "unix:acme/host.sock", http = ())),
    (name = "egressDeny", external = (address = "unix:acme/egress-deny.sock", http = ())),
    (name = "egress0", external = (address = "unix:acme/egress-0.sock", http = ())),
    (name = "egress1", external = (address = "unix:acme/egress-1.sock", http = ())),
    (name = "egress2", external = (address = "unix:acme/egress-2.sock", http = ())),
    (name = "egress3", external = (address = "unix:acme/egress-3.sock", http = ())),
    (name = "egress4", external = (address = "unix:acme/egress-4.sock", http = ())),
    (name = "egress5", external = (address = "unix:acme/egress-5.sock", http = ())),
    (name = "egress6", external = (address = "unix:acme/egress-6.sock", http = ())),
    (name = "egress7", external = (address = "unix:acme/egress-7.sock", http = ())),
    (name = "egress8", external = (address = "unix:acme/egress-8.sock", http = ())),
    (name = "egress9", external = (address = "unix:acme/egress-9.sock", http = ())),
    (name = "egress10", external = (address = "unix:acme/egress-10.sock", http = ())),
    (name = "egress11", external = (address = "unix:acme/egress-11.sock", http = ())),
    (name = "egress12", external = (address = "unix:acme/egress-12.sock", http = ())),
    (name = "egress13", external = (address = "unix:acme/egress-13.sock", http = ())),
    (name = "egress14", external = (address = "unix:acme/egress-14.sock", http = ())),
    (name = "egress15", external = (address = "unix:acme/egress-15.sock", http = ())),
    (name = "egress16", external = (address = "unix:acme/egress-16.sock", http = ())),
    (name = "egress17", external = (address = "unix:acme/egress-17.sock", http = ())),
    (name = "egress18", external = (address = "unix:acme/egress-18.sock", http = ())),
    (name = "egress19", external = (address = "unix:acme/egress-19.sock", http = ())),
    (name = "egress20", external = (address = "unix:acme/egress-20.sock", http = ())),
    (name = "egress21", external = (address = "unix:acme/egress-21.sock", http = ())),
    (name = "egress22", external = (address = "unix:acme/egress-22.sock", http = ())),
    (name = "egress23", external = (address = "unix:acme/egress-23.sock", http = ())),
    (name = "egress24", external = (address = "unix:acme/egress-24.sock", http = ())),
    (name = "egress25", external = (address = "unix:acme/egress-25.sock", http = ())),
    (name = "egress26", external = (address = "unix:acme/egress-26.sock", http = ())),
    (name = "egress27", external = (address = "unix:acme/egress-27.sock", http = ())),
    (name = "egress28", external = (address = "unix:acme/egress-28.sock", http = ())),
    (name = "egress29", external = (address = "unix:acme/egress-29.sock", http = ())),
    (name = "egress30", external = (address = "unix:acme/egress-30.sock", http = ())),
    (name = "egress31", external = (address = "unix:acme/egress-31.sock", http = ())),
    (name = "egress32", external = (address = "unix:acme/egress-32.sock", http = ())),
    (name = "egress33", external = (address = "unix:acme/egress-33.sock", http = ())),
    (name = "egress34", external = (address = "unix:acme/egress-34.sock", http = ())),
    (name = "egress35", external = (address = "unix:acme/egress-35.sock", http = ())),
    (name = "egress36", external = (address = "unix:acme/egress-36.sock", http = ())),
    (name = "egress37", external = (address = "unix:acme/egress-37.sock", http = ())),
    (name = "egress38", external = (address = "unix:acme/egress-38.sock", http = ())),
    (name = "egress39", external = (address = "unix:acme/egress-39.sock", http = ())),
    (name = "egress40", external = (address = "unix:acme/egress-40.sock", http = ())),
    (name = "egress41", external = (address = "unix:acme/egress-41.sock", http = ())),
    (name = "egress42", external = (address = "unix:acme/egress-42.sock", http = ())),
    (name = "egress43", external = (address = "unix:acme/egress-43.sock", http = ())),
    (name = "egress44", external = (address = "unix:acme/egress-44.sock", http = ())),
    (name = "egress45", external = (address = "unix:acme/egress-45.sock", http = ())),
    (name = "egress46", external = (address = "unix:acme/egress-46.sock", http = ())),
    (name = "egress47", external = (address = "unix:acme/egress-47.sock", http = ())),
    (name = "egress48", external = (address = "unix:acme/egress-48.sock", http = ())),
    (name = "egress49", external = (address = "unix:acme/egress-49.sock", http = ())),
    (name = "egress50", external = (address = "unix:acme/egress-50.sock", http = ())),
    (name = "egress51", external = (address = "unix:acme/egress-51.sock", http = ())),
    (name = "egress52", external = (address = "unix:acme/egress-52.sock", http = ())),
    (name = "egress53", external = (address = "unix:acme/egress-53.sock", http = ())),
    (name = "egress54", external = (address = "unix:acme/egress-54.sock", http = ())),
    (name = "egress55", external = (address = "unix:acme/egress-55.sock", http = ())),
    (name = "egress56", external = (address = "unix:acme/egress-56.sock", http = ())),
    (name = "egress57", external = (address = "unix:acme/egress-57.sock", http = ())),
    (name = "egress58", external = (address = "unix:acme/egress-58.sock", http = ())),
    (name = "egress59", external = (address = "unix:acme/egress-59.sock", http = ())),
    (name = "egress60", external = (address = "unix:acme/egress-60.sock", http = ())),
    (name = "egress61", external = (address = "unix:acme/egress-61.sock", http = ())),
    (name = "egress62", external = (address = "unix:acme/egress-62.sock", http = ())),
    (name = "egress63", external = (address = "unix:acme/egress-63.sock", http = ())),
  ],
  sockets = [
    (name = "control", address = "unix:acme/control.sock", http = (), service = "controller"),
  ]
);
const controller :Workerd.Worker = (
  modules = [ (name = "controller.js", esModule = embed "controller.js") ],
  compatibilityDate = "2026-01-01",
  compatibilityFlags = ["experimental"],
  bindings = [
    (name = "LOADER", workerLoader = (id = "acme")),
    (name = "HOST", service = "host"),
    (name = "EGRESS_DENY", service = "egressDeny"),
    (name = "EGRESS_0", service = "egress0"),
    (name = "EGRESS_1", service = "egress1"),
    (name = "EGRESS_2", service = "egress2"),
    (name = "EGRESS_3", service = "egress3"),
    (name = "EGRESS_4", service = "egress4"),
    (name = "EGRESS_5", service = "egress5"),
    (name = "EGRESS_6", service = "egress6"),
    (name = "EGRESS_7", service = "egress7"),
    (name = "EGRESS_8", service = "egress8"),
    (name = "EGRESS_9", service = "egress9"),
    (name = "EGRESS_10", service = "egress10"),
    (name = "EGRESS_11", service = "egress11"),
    (name = "EGRESS_12", service = "egress12"),
    (name = "EGRESS_13", service = "egress13"),
    (name = "EGRESS_14", service = "egress14"),
    (name = "EGRESS_15", service = "egress15"),
    (name = "EGRESS_16", service = "egress16"),
    (name = "EGRESS_17", service = "egress17"),
    (name = "EGRESS_18", service = "egress18"),
    (name = "EGRESS_19", service = "egress19"),
    (name = "EGRESS_20", service = "egress20"),
    (name = "EGRESS_21", service = "egress21"),
    (name = "EGRESS_22", service = "egress22"),
    (name = "EGRESS_23", service = "egress23"),
    (name = "EGRESS_24", service = "egress24"),
    (name = "EGRESS_25", service = "egress25"),
    (name = "EGRESS_26", service = "egress26"),
    (name = "EGRESS_27", service = "egress27"),
    (name = "EGRESS_28", service = "egress28"),
    (name = "EGRESS_29", service = "egress29"),
    (name = "EGRESS_30", service = "egress30"),
    (name = "EGRESS_31", service = "egress31"),
    (name = "EGRESS_32", service = "egress32"),
    (name = "EGRESS_33", service = "egress33"),
    (name = "EGRESS_34", service = "egress34"),
    (name = "EGRESS_35", service = "egress35"),
    (name = "EGRESS_36", service = "egress36"),
    (name = "EGRESS_37", service = "egress37"),
    (name = "EGRESS_38", service = "egress38"),
    (name = "EGRESS_39", service = "egress39"),
    (name = "EGRESS_40", service = "egress40"),
    (name = "EGRESS_41", service = "egress41"),
    (name = "EGRESS_42", service = "egress42"),
    (name = "EGRESS_43", service = "egress43"),
    (name = "EGRESS_44", service = "egress44"),
    (name = "EGRESS_45", service = "egress45"),
    (name = "EGRESS_46", service = "egress46"),
    (name = "EGRESS_47", service = "egress47"),
    (name = "EGRESS_48", service = "egress48"),
    (name = "EGRESS_49", service = "egress49"),
    (name = "EGRESS_50", service = "egress50"),
    (name = "EGRESS_51", service = "egress51"),
    (name = "EGRESS_52", service = "egress52"),
    (name = "EGRESS_53", service = "egress53"),
    (name = "EGRESS_54", service = "egress54"),
    (name = "EGRESS_55", service = "egress55"),
    (name = "EGRESS_56", service = "egress56"),
    (name = "EGRESS_57", service = "egress57"),
    (name = "EGRESS_58", service = "egress58"),
    (name = "EGRESS_59", service = "egress59"),
    (name = "EGRESS_60", service = "egress60"),
    (name = "EGRESS_61", service = "egress61"),
    (name = "EGRESS_62", service = "egress62"),
    (name = "EGRESS_63", service = "egress63"),
  ],
);
