package wasm

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
	"time"
)

// ensureWasip1HTTPWasm returns the path to the wasip1 HTTP guest, compiling it
// from the committed source when it isn't already on disk.
//
// The binary is gitignored and regenerated by whichever package needs it. The
// driver tests used to skip-if-missing, which made their coverage depend on
// package run order: `go test ./...` runs packages as separate processes, so
// these tests only executed when pkg/wasm or pkg/wasm/worker happened to
// compile the artifact into the shared checkout first. In CI that meant the
// HTTP expose and /work+listen paths could go silently untested. Compiling on
// demand — the same pattern as the pkg/wasm and pkg/wasm/worker helpers —
// makes the coverage unconditional.
//
// Skips (not failures) are reserved for environments that genuinely cannot
// produce the artifact: Windows, or a checkout without the guest source.
func ensureWasip1HTTPWasm(t *testing.T) string {
	t.Helper()
	// Absolute output: the build runs with cmd.Dir = the guest source dir, so a
	// relative -o would land next to the source instead of in pkg/wasm/testdata.
	out, err := filepath.Abs(filepath.Join("..", "..", "..", "pkg", "wasm", "testdata", "wasip1-http.wasm"))
	if err != nil {
		t.Fatal(err)
	}
	if st, err := os.Stat(out); err == nil && st.Size() > 0 {
		return out
	}
	if runtime.GOOS == "windows" {
		t.Skip("wasip1-http.wasm compile skipped on windows")
	}
	src, err := filepath.Abs(filepath.Join("..", "..", "..", "pkg", "wasm", "testdata", "aerolhttp"))
	if err != nil {
		t.Fatal(err)
	}
	if st, err := os.Stat(src); err != nil || !st.IsDir() {
		t.Skip("aerolhttp wasip1 guest source missing")
	}
	// A missing toolchain is an environment limitation, not a defect under
	// test — same class as Windows above. Checked before the build so the
	// failure mode is a clear skip rather than a confusing exec error.
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain unavailable; cannot compile wasip1-http.wasm")
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, "go", "build", "-o", out, ".")
	cmd.Env = append(os.Environ(), "GOOS=wasip1", "GOARCH=wasm")
	cmd.Dir = src
	if combined, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("compile wasip1-http.wasm: %v\n%s", err, combined)
	}
	return out
}
