// Package inspect holds the egress gateway's per-node inspection CA
// (plans/egress-domain-filtering.md §5.9, P3-1). sandboxd generates the CA
// once per node and keeps its key sealed; the gateway is handed the key over
// its UDS and mints a short-lived leaf for each inspected name, so the proxy
// can terminate TLS for hosts with inspect rules. Only sandboxes created with
// inspect rules trust the CA.
package inspect

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"net/netip"
	"strings"
	"sync"
	"time"
)

const (
	// caLifetime is long: rotating the CA means recreating every sandbox
	// that trusts it, so it is a deliberate operator act, not a timer.
	caLifetime = 10 * 365 * 24 * time.Hour
	// leafLifetime keeps a leaf short-lived; leafRenew reissues before a
	// client could see it expire mid-session.
	leafLifetime = 24 * time.Hour
	leafRenew    = time.Hour
	leafBackdate = time.Hour
	// maxCachedLeaves bounds the leaf cache; past it the cache starts over.
	maxCachedLeaves = 4096
)

// GenerateCA creates a self-signed CA certificate and its key, both PEM.
func GenerateCA(commonName string, now time.Time) (certPEM, keyPEM []byte, err error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("inspection CA key: %w", err)
	}
	// A nil serial and subject key ID are generated by CreateCertificate.
	tmpl := &x509.Certificate{
		Subject:               pkix.Name{CommonName: commonName, Organization: []string{"AerolVM egress inspection"}},
		NotBefore:             now.Add(-leafBackdate),
		NotAfter:              now.Add(caLifetime),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLenZero:        true,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, nil, fmt.Errorf("inspection CA certificate: %w", err)
	}
	keyDER, _ := x509.MarshalECPrivateKey(key) // P-256 always marshals
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}),
		pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER}), nil
}

// Authority mints leaf certificates under a CA.
type Authority struct {
	ca      *x509.Certificate
	caKey   *ecdsa.PrivateKey
	caPEM   []byte
	leafKey *ecdsa.PrivateKey
	now     func() time.Time

	mu    sync.Mutex
	cache map[string]*tls.Certificate
}

// New loads a CA from PEM. now may be nil (time.Now).
func New(certPEM, keyPEM []byte, now func() time.Time) (*Authority, error) {
	cb, _ := pem.Decode(certPEM)
	if cb == nil || cb.Type != "CERTIFICATE" {
		return nil, errors.New("inspection CA: no certificate PEM")
	}
	ca, err := x509.ParseCertificate(cb.Bytes)
	if err != nil {
		return nil, fmt.Errorf("inspection CA: %w", err)
	}
	if !ca.IsCA {
		return nil, errors.New("inspection CA: certificate is not a CA")
	}
	kb, _ := pem.Decode(keyPEM)
	if kb == nil {
		return nil, errors.New("inspection CA: no key PEM")
	}
	key, err := x509.ParseECPrivateKey(kb.Bytes)
	if err != nil {
		return nil, fmt.Errorf("inspection CA key: %w", err)
	}
	if !key.PublicKey.Equal(ca.PublicKey) {
		return nil, errors.New("inspection CA: key does not match the certificate")
	}
	// One leaf key for every leaf: minting is then a signature, not a key
	// generation, so the first connection to a new name stays fast.
	leafKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("inspection leaf key: %w", err)
	}
	if now == nil {
		now = time.Now
	}
	return &Authority{ca: ca, caKey: key, caPEM: append([]byte(nil), certPEM...), leafKey: leafKey, now: now,
		cache: map[string]*tls.Certificate{}}, nil
}

// CertPEM is the CA certificate sandboxes trust.
func (a *Authority) CertPEM() []byte { return append([]byte(nil), a.caPEM...) }

// Leaf returns a certificate for host signed by the CA, from the cache
// while it has more than leafRenew left.
func (a *Authority) Leaf(host string) (*tls.Certificate, error) {
	host = strings.ToLower(strings.TrimSuffix(host, "."))
	if host == "" {
		return nil, errors.New("inspection: no server name")
	}
	now := a.now()
	a.mu.Lock()
	defer a.mu.Unlock()
	if c, ok := a.cache[host]; ok && now.Before(c.Leaf.NotAfter.Add(-leafRenew)) {
		return c, nil
	}
	tmpl := &x509.Certificate{
		Subject:     pkix.Name{CommonName: host},
		NotBefore:   now.Add(-leafBackdate),
		NotAfter:    now.Add(leafLifetime),
		KeyUsage:    x509.KeyUsageDigitalSignature,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	if ip, err := netip.ParseAddr(host); err == nil {
		tmpl.IPAddresses = append(tmpl.IPAddresses, ip.AsSlice())
	} else {
		tmpl.DNSNames = []string{host}
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, a.ca, &a.leafKey.PublicKey, a.caKey)
	if err != nil {
		return nil, fmt.Errorf("inspection leaf for %s: %w", host, err)
	}
	leaf, _ := x509.ParseCertificate(der) // just created
	c := &tls.Certificate{Certificate: [][]byte{der, a.ca.Raw}, PrivateKey: a.leafKey, Leaf: leaf}
	if len(a.cache) >= maxCachedLeaves {
		a.cache = map[string]*tls.Certificate{}
	}
	a.cache[host] = c
	return c, nil
}
