package safety

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The node bootstrap is a ~460-line bash script generated by Terraform from
// templates/bootstrap.sh.tftpl, and nothing else checks the result.
// `terraform validate` proves only that the TEMPLATE parses — it says nothing
// about the bash that falls out of it, and the first thing that ever runs that
// bash is cloud-init on a real EC2 box, where a typo surfaces as a node that
// half-bootstrapped and a scenario that times out 10 minutes later.
//
// This renders both branches (seed and joiner — they differ substantially,
// and the CSR signing rendezvous lives entirely in the two halves) and runs
// `bash -n` over each. It caught an unescaped `${aws:userid}` in a comment
// while the rendezvous was being written.
//
// Skips when terraform is not installed, so `make test` stays runnable without
// it. No network and no AWS: the fixture declares no providers, so
// `terraform init -backend=false` is offline.
func TestBootstrapTemplateRenders(t *testing.T) {
	tf, err := exec.LookPath("terraform")
	if err != nil {
		t.Skip("terraform not on PATH; skipping bootstrap template render check")
	}
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not on PATH")
	}

	repoRoot := filepath.Join(filepath.Dir(buildScript(t)), "..", "..")
	tplPath, err := filepath.Abs(filepath.Join(repoRoot, "Terraform", "templates", "bootstrap.sh.tftpl"))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(tplPath); err != nil {
		t.Fatalf("bootstrap template missing: %v", err)
	}

	fixture, err := os.ReadFile(filepath.Join("testdata", "bootstrap_render", "main.tf"))
	if err != nil {
		t.Fatal(err)
	}

	dir := t.TempDir()
	rendered := strings.ReplaceAll(string(fixture), "__TEMPLATE__", tplPath)
	if err := os.WriteFile(filepath.Join(dir, "main.tf"), []byte(rendered), 0o644); err != nil {
		t.Fatal(err)
	}

	run := func(args ...string) (string, error) {
		cmd := exec.Command(tf, args...)
		cmd.Dir = dir
		// Keep terraform from reading the operator's real CLI config / plugin
		// cache, and from phoning home.
		cmd.Env = append(os.Environ(), "TF_IN_AUTOMATION=1", "CHECKPOINT_DISABLE=1")
		out, err := cmd.CombinedOutput()
		return string(out), err
	}

	if out, err := run("init", "-backend=false", "-input=false"); err != nil {
		t.Fatalf("terraform init: %v\n%s", err, out)
	}
	if out, err := run("apply", "-auto-approve", "-input=false"); err != nil {
		// A missing variable lands here and names itself, which is the intended
		// signal when someone adds one to nodes.tf without updating testdata.
		t.Fatalf("rendering bootstrap.sh.tftpl failed: %v\n%s", err, out)
	}

	for _, branch := range []string{"seed", "joiner"} {
		t.Run(branch, func(t *testing.T) {
			out, err := run("output", "-raw", branch)
			if err != nil {
				t.Fatalf("terraform output %s: %v\n%s", branch, err, out)
			}
			script := filepath.Join(dir, branch+".sh")
			if err := os.WriteFile(script, []byte(out), 0o644); err != nil {
				t.Fatal(err)
			}
			if lint, err := exec.Command("bash", "-n", script).CombinedOutput(); err != nil {
				t.Fatalf("rendered %s bootstrap is not valid bash: %v\n%s", branch, err, lint)
			}

			// `bash -n` on the outer script does NOT parse the body of a
			// QUOTED heredoc — it is literal text there. The seed embeds the
			// CSR signing loop that way, which makes the most intricate new
			// script in this template the one piece the outer lint cannot see.
			// Extract and check it on its own.
			for name, body := range embeddedHeredocs(out) {
				inner := filepath.Join(dir, branch+"-"+name+".sh")
				if err := os.WriteFile(inner, []byte(body), 0o644); err != nil {
					t.Fatal(err)
				}
				if lint, err := exec.Command("bash", "-n", inner).CombinedOutput(); err != nil {
					t.Errorf("embedded %s script in the %s bootstrap is not valid bash: %v\n%s",
						name, branch, err, lint)
				}
			}

			// Spot-check the pieces the CSR rendezvous depends on, so a
			// refactor that drops one fails here rather than on a cluster that
			// never forms.
			mustContain := map[string][]string{
				"seed": {
					"--cred-bundle-out /tmp/aerolvm-cred-bundle.tar.gz",
					"aerolvm-cred-bundle.tar.gz",
					"aerolvm-csr-signer",
					"cluster-sign-node.sh",
					// The id must come from the Terraform-written mapping,
					// never from the uploader's path or CSR.
					"nodes/$ident",
				},
				"joiner": {
					"--cred-bundle /tmp/aerolvm-cred-bundle.tar.gz",
					"--signed-cert /tmp/node.crt",
					"/etc/sandboxd/tls/node.csr",
					"EXPECTED_IDENT",
					// exit 2 is cluster-join's "CSR ready" signal and must be
					// treated as success, not failure.
					`"$join_rc" -ne 2`,
				},
			}
			for _, want := range mustContain[branch] {
				if !strings.Contains(out, want) {
					t.Errorf("rendered %s bootstrap is missing %q", branch, want)
				}
			}
		})
	}
}

// embeddedHeredocs returns the body of every quoted heredoc written with
// `<<'NAME'`, keyed by NAME. Those bodies are opaque to a `bash -n` of the
// enclosing script, so they have to be linted separately.
func embeddedHeredocs(script string) map[string]string {
	out := map[string]string{}
	lines := strings.Split(script, "\n")
	for i := 0; i < len(lines); i++ {
		open := strings.Index(lines[i], "<<'")
		if open < 0 {
			continue
		}
		rest := lines[i][open+3:]
		end := strings.Index(rest, "'")
		if end <= 0 {
			continue
		}
		name := rest[:end]
		// Only bother with bodies that look like shell; a systemd unit or a
		// JSON blob written this way would fail `bash -n` for no good reason.
		var body []string
		closed := false
		for j := i + 1; j < len(lines); j++ {
			if strings.TrimSpace(lines[j]) == name {
				closed = true
				i = j
				break
			}
			body = append(body, lines[j])
		}
		if !closed || len(body) == 0 {
			continue
		}
		if !strings.HasPrefix(strings.TrimSpace(body[0]), "#!") {
			continue
		}
		out[name] = strings.Join(body, "\n")
	}
	return out
}

// The extra_sandboxd_env map must land in cluster.env BEFORE the bootstrap's
// final `systemctl restart sandboxd`. That ordering is the entire point of the
// variable: extra_user_data, the only previous lever, runs AFTER that restart,
// so setting any SB_* meant appending to the env file and restarting a second
// time — workable for one flag, unusable as the mechanism for a profile matrix.
func TestBootstrapRendersExtraSandboxdEnvBeforeRestart(t *testing.T) {
	tf, err := exec.LookPath("terraform")
	if err != nil {
		t.Skip("terraform not on PATH")
	}
	repoRoot := filepath.Join(filepath.Dir(buildScript(t)), "..", "..")
	tplPath, _ := filepath.Abs(filepath.Join(repoRoot, "Terraform", "templates", "bootstrap.sh.tftpl"))
	fixture, err := os.ReadFile(filepath.Join("testdata", "bootstrap_render", "main.tf"))
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "main.tf"),
		[]byte(strings.ReplaceAll(string(fixture), "__TEMPLATE__", tplPath)), 0o644); err != nil {
		t.Fatal(err)
	}
	run := func(args ...string) (string, error) {
		cmd := exec.Command(tf, args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "TF_IN_AUTOMATION=1", "CHECKPOINT_DISABLE=1")
		out, err := cmd.CombinedOutput()
		return string(out), err
	}
	if out, err := run("init", "-backend=false", "-input=false"); err != nil {
		t.Fatalf("terraform init: %v\n%s", err, out)
	}
	if out, err := run("apply", "-auto-approve", "-input=false"); err != nil {
		t.Fatalf("apply: %v\n%s", err, out)
	}
	out, err := run("output", "-raw", "joiner")
	if err != nil {
		t.Fatalf("output: %v\n%s", err, out)
	}

	// The fixture sets these two through sandboxd_env.
	envIdx := strings.Index(out, "SB_SECRET_PROVIDER=awskms")
	if envIdx < 0 {
		t.Fatal("sandboxd_env entries were not rendered into the ops-env block")
	}
	if !strings.Contains(out, "SB_ENTERPRISE_MODE=true") {
		t.Error("second sandboxd_env entry missing")
	}
	teeIdx := strings.Index(out, "tee -a /etc/sandboxd/cluster.env")
	restartIdx := strings.LastIndex(out, "\nsudo systemctl restart sandboxd\n")
	if teeIdx < 0 || restartIdx < 0 {
		t.Fatalf("could not locate the env write (%d) or the final restart (%d)", teeIdx, restartIdx)
	}
	if !(envIdx < teeIdx && teeIdx < restartIdx) {
		t.Fatalf("sandboxd_env must be written into cluster.env before the final restart; got env=%d tee=%d restart=%d",
			envIdx, teeIdx, restartIdx)
	}
}
